package dames;
// Generated 27/02/2020 16:49:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Damas generated by hbm2java
 */
public class Damas  implements java.io.Serializable {


     private Integer id;
     private Date data;
     private char guanyador;
     private Set movimentses = new HashSet(0);

    public Damas() {
    }

    public Damas(char guanyador) {
        this.guanyador = guanyador;
    }
	
    public Damas(Date data, char guanyador) {
        this.data = data;
        this.guanyador = guanyador;
    }
    public Damas(Date data, char guanyador, Set movimentses) {
       this.data = data;
       this.guanyador = guanyador;
       this.movimentses = movimentses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public char getGuanyador() {
        return this.guanyador;
    }
    
    public void setGuanyador(char guanyador) {
        this.guanyador = guanyador;
    }
    public Set getMovimentses() {
        return this.movimentses;
    }
    
    public void setMovimentses(Set movimentses) {
        this.movimentses = movimentses;
    }




}


